language: node_js

node_js: 
  - 12.16.3
cache: npm

install:
  - npm install
script:
  local_dir: client
  - sonar-scanner
  # - npm run all-unit-tests
  # - npm run build
addons:
  sonarcloud:
    organization: "dynamic-learning"
    token:
      secure: "**************************" 
